### PR TITLE
Spicy's UI Changes and fixes

### PR DESCRIPTION
**Pull request by SpicyForthProgrammer**
Why not  - in regards to my fedora commit.

### CODE REVIEW

**Comment by SpicyForthProgrammer** [comment]
**### PLEASE READ BEFORE MERGING**
THIS IS BUGGED!
I can't figure out how to regenerate the sandbox menu icons so things will not show up correctly when compiled.

### Changes to menu:
Everything was reorganized according to function. With categories being made smaller to make finding specific objects easier. I am more than open to suggestions for changes in this regard. I'm still not 100% on the gates organization. 

Here is the spreadsheet I made for the sorting: [https://docs.google.com/spreadsheets/d/1G1qBfMv8ShjMe1808msqZHuCXQawUn455e2lljZFCck/edit?usp=sharing)](Spreadhsheet)

Please make sure I didn't forget any objects

**Comment by SpicyForthProgrammer** [comment]
Hopefully this will help with my goal of making the game more intuitive.

**Comment by SpicyForthProgrammer** [comment]
Another bug, the game wont render more than a few categories

**Comment by SpicyForthProgrammer** [comment]
Well now this is segfaulting on launch

**Comment by SpicyForthProgrammer** [comment]
something is making the text render segfault

**Comment by rollerozxa** [comment]
> I can't figure out how to regenerate the sandbox menu icons so things will not show up correctly when compiled.

They can be generated in debug builds when pressing S on the main menu but things need to be set up properly first before that will work, having to move one directory up to launch the game breaks the script that is being used to process the sandbox menu images after the game has generated them.

**Comment by sdac** [comment]
imo let's wait with this until we've published a release, right now people are asking about prebuilt window and android etc

**Comment by SpicyForthProgrammer** [comment]
Yeah sure, I'm just keeping it here. But it made me notice that the ui is fairly buggy.

**Comment by ParamonPlay2205** [comment]
I recently made a pull request for build dependencies on Fedora (note that I did not see this pull request when I made mine). And with the dependencies I specified, I compiled it with no problems related to dependencies. And it doesn't seem to be buggy at all on my end.

**Pull request closed without merging**
